<?php


namespace app\components;

use yii\base\Widget;

class ClassList extends Widget
{
    public $subject;
    public $begin;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        switch ($this->subject) {
            case 1:
            case 2:
            case 3:
            case 10: { $this->begin = 1; break; }
            case 5: { $this->begin = 2; break; }
            case 4: { $this->begin = 3; break; }
            case 11: { $this->begin = 4; break; }
            case 8:
            case 9: { $this->begin = 5; break; }
            case 6: { $this->begin = 6; break; }
            case 7: { $this->begin = 7; break; }
        }
    }

    public function run()
    {
        echo '<div id="classList">';
        for ($i = $this->begin; $i <= 11; $i++) {
            echo '<a href="#" class="classFilter"><span class="classNum">'.$i.'</span><span>класс</span></a>';
        }
        echo '</div>';
    }
}
