<?php


namespace app\widgets;


use yii\base\Widget;
use yii\helpers\Html;

class Banner extends Widget
{
    public $subject;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        switch ($this->subject) {
            case 1:

        }
    }
}